### ISSUE TITLE
The gsd-backlight-helper exec path is changed in gnome-settings-daemon 3.28

### ISSUE THREAD

**Issue by zhangkaizhao** [ilgarmehmetali/budgie-brightness-control-applet#11]
The `gsd-backlight-helper` exec path from package `gnome-settings-daemon` version 3.28 is located in `libexecdir` now.

Patch on Arch Linux:

https://aur.archlinux.org/cgit/aur.git/tree/gsd-backlight-helper.patch?h=budgie-brightness-control-applet

Arch Linux:

https://www.archlinux.org/packages/extra/x86_64/gnome-settings-daemon/#pkgfiles
https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/gnome-settings-daemon

Fedora:

https://github.com/alunux/rpm-specfiles/blob/master/budgie-desktop-plugin-extras/0002-fix-gsd-backlight-helper-path-on-fedora.patch

See:

https://gitlab.gnome.org/GNOME/gnome-settings-daemon/blob/GNOME_SETTINGS_DAEMON_3_28_1/meson.build#L21
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/blob/GNOME_SETTINGS_DAEMON_3_28_1/plugins/power/meson.build#L89

**Comment by ilgarmehmetali** [comment]
Thanks, made a new release.
Seeing an aur package made happy, thanks for that too.
