### ISSUE TITLE
slider control

### ISSUE THREAD

**Issue by fossfreedom** [ilgarmehmetali/budgie-brightness-control-applet#2]
suggestion - add a slider between the + and - buttons to allow a user to change the brightness via dragging.

**Comment by ilgarmehmetali** [comment]
there should already be one though, this applet should look exactly like volume control applet or does slider not appear for you?

**Comment by fossfreedom** [comment]
the volume control applet displays fine.

I see this with brightness-control

![workspace 1_036](https://user-images.githubusercontent.com/996240/27009792-de58ba3e-4e8e-11e7-8a82-275dc2183659.jpg)

(GTK+3.22 Ubuntu Budgie 17.04)

**Comment by ilgarmehmetali** [comment]
Can you check what does the command bellow prints when you run it in terminal?
pkexec /usr/lib/gnome-settings-daemon/gsd-backlight-helper --get-max-brightness

**Comment by fossfreedom** [comment]
ah - its probably because I'm building and running this in my test VM?

returned is "Could not get or set the value of the backlight: No backlight devices present"

**Comment by ilgarmehmetali** [comment]
yep that should be it
