### ISSUE TITLE
Copyright & License Requirements

### ISSUE THREAD

**Issue by ikeydoherty** [ilgarmehmetali/budgie-brightness-control-applet#4]
Hi, this is a pretty cool applet, but you must understand that you've effectively forked my code to
create this applet, and the headers which are required by the GPL to be _preserved_ are absent
from your source files.

i.e. the ones that explain the license and actually attribute the code to relevant authors. In effect, the license of the original code is mine to give, and you extend upon it with your changes. So if someone forks your code in future, then the whole chain of custody and ownership is respected, and the license remains valid.

**Comment by ilgarmehmetali** [comment]
Hi Ikey, thanks for letting me know of this. I thought mentioning where i derived it inside readme file and releasing it with the same license would do the trick.
I can add header info mentioning you as the original author, where i derived it from and license info asap.

**Comment by ikeydoherty** [comment]
No rush on it - and let me be clear, I'm not annoyed either. It just helps you get into the habit of ensuring the requirements are met (i.e. keeping the notice in place) - saves you putting up with the same crap later on down the line from someone who is bothered and makes a fuss :P

**Comment by ilgarmehmetali** [comment]
Ikey can you check if this is a good format, im not familiar with any convention with forked code
https://github.com/ilgarmehmetali/budgie-brightness-control-applet/commit/420fa7c0277a0edf7229b19bf4f214590df2444e

**Comment by ikeydoherty** [comment]
LGTM :)
