### ISSUE TITLE
heads up - GTK Popover replaced by BudgiePopover

### ISSUE THREAD

**Issue by fossfreedom** [ilgarmehmetali/budgie-brightness-control-applet#5]
Quick heads up ... I'm sure you are already aware...

In master Git (budgie-desktop) - pending a new release of budgie-desktop, all applets that have popovers will need slight tweaks to make them work with the new API/ABI

Please can I ask 2 things?:

1. push a git tag release for this applet for users of budgie-desktop 10.2.9 - 10.3.1 
2. have a look at the new API/ABI and prepare for the new budgie-desktop version

cheers

**Comment by ilgarmehmetali** [comment]
Took care of this after ages :D
Also changed the ui to match 10.4 sound indicator
