### ISSUE TITLE
Unable to install applet

### ISSUE THREAD

**Issue by rainer2208** [ilgarmehmetali/budgie-brightness-control-applet#9]
I am trying to install the applet. Going through the installation process, after typing (copying and pasting) : 

meson --prefix /usr --buildtype=plain .. 

I get the error message: "Neither directory contains a build file meson.build."

What am I missing?

**Comment by ilgarmehmetali** [comment]
You should run those commands in source directory after cloning the repo
```

git clone git@github.com:ilgarmehmetali/budgie-brightness-control-applet.git
cd budgie-brightness-control-applet

mkdir build && cd build
meson --prefix /usr --buildtype=plain ..
ninja
sudo ninja install
```

**Comment by rainer2208** [comment]
Ok, thanks, went through it. Unfortunately, after cloning the repo and running 

    meson --prefix /usr --buildtype=plain .. 

from within 

    /build/budgie-brightness-control-applet

I get another error message:

    Meson encountered an error in file meson.build, line 1, column 0:
    Could not execute Vala compiler "valac"

**Comment by ilgarmehmetali** [comment]
You need vala to be installed in your system.

**Comment by rainer2208** [comment]
Thanks for looking into this. My feedback would be finding a more simple way to obtain or install your nice applet. To me, it seems a little too much work and hassle.

**Comment by ilgarmehmetali** [comment]
May i ask what your os is?

**Comment by rainer2208** [comment]
Of course. My OS is Ubuntu 17.04 .....
